version: 0.2

phases:
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/buildspecs/
      - ls -al
      - echo "Preparing environment"
      - chmod +x process_raw_reports.sh

  build:
    commands:
      - ./process_raw_reports.sh

artifacts:
  files:
    - summary-report.json
  base-directory: .
