version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Running SonarQube"
      - echo "Generated report" > sonarqube-report.txt
artifacts:
  files:
    - sonarqube-report.txt
