version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies for Secret Scanning..."
      - pip install --upgrade trufflehog3

  build:
    commands:
      - echo "Starting TruffleHog scan for secret keys..."
      - |
        trufflehog3 -f json -o trufflehog_output.json || true 

  post_build:
    commands:
      - echo "Checking scan results..."
      - TIMESTAMP=$(date +%Y-%m-%d-%H-%M)

      - if [ -f "trufflehog_output.json" ]; then
          echo "Uploading scan results to S3...";
          aws s3 cp trufflehog_output.json s3://${RESULTS_BUCKET}/trufflehog/${TIMESTAMP}/trufflehog_output.json;
        else
          echo "Scan results not found, creating an empty one...";
          echo '{"Results":[]}' > trufflehog_output.json;
          aws s3 cp trufflehog_output.json s3://${RESULTS_BUCKET}/trufflehog/${TIMESTAMP}/trufflehog_output.json;
        fi

artifacts:
  files:
    - trufflehog_output.json
  base-directory: .

